config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patients do
    resources :pre_existing_conditions
    resources :food_allergies
    resources :drug_allergies
  end
  devise_for :doctors
  root to: "doctors#index"

  devise_scope :doctor do
    get '/doctors/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/drug_allergy.rb
class DrugAllergy < ApplicationRecord
  belongs_to :patient
end

app/controllers/drug_allergies_controller.rb
class DrugAllergiesController < ApplicationController
  before_action :set_patient
  before_action :set_drug_allergy, only: %i[show edit update destroy]

  # GET patients/1/drug_allergies
  def index
    @drug_allergies = @patient.drug_allergies
  end

  # GET patients/1/drug_allergies/1
  def show; end

  # GET patients/1/drug_allergies/new
  def new
    @drug_allergy = @patient.drug_allergies.build
  end

  # GET patients/1/drug_allergies/1/edit
  def edit; end

  # POST patients/1/drug_allergies
  def create
    @drug_allergy = @patient.drug_allergies.build(drug_allergy_params)

    if @drug_allergy.save
      redirect_to(@drug_allergy.patient)
    else
      render action: 'new'
    end
  end

  # PUT patients/1/drug_allergies/1
  def update
    if @drug_allergy.update_attributes(drug_allergy_params)
      redirect_to([@drug_allergy.patient, @drug_allergy], notice: 'Drug allergy was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE patients/1/drug_allergies/1
  def destroy
    @drug_allergy.destroy

    redirect_to patient_drug_allergies_url(@patient)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def set_drug_allergy
    @drug_allergy = @patient.drug_allergies.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def drug_allergy_params
    params.require(:drug_allergy).permit(:name, :patient_id)
  end
end

app/views/drug_allergies/_form.html.erb
<%= form_for([@drug_allergy.patient, @drug_allergy]) do |f| %>
  <% if @drug_allergy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug_allergy.errors.count, "error") %> prohibited this drug_allergy from being saved:</h2>

      <ul>
      <% @drug_allergy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
        
  <%= f.text_field :name %>
</div>


<div class="text-center">
<%= f.submit  class: "btn btn-primary my-3" %>
</div>
<% end %>

app/views/drug_allergies/edit.html.erb
<h1>Editing drug_allergy</h1>

<%= render 'form' %>

<%= link_to 'Show', [@drug_allergy.patient, @drug_allergy] %> |
<%= link_to 'Back', patient_drug_allergies_path(@drug_allergy.patient) %>

app/views/drug_allergies/index.html.erb
<h1>Listing drug_allergies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Patient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drug_allergies.each do |drug_allergy| %>
  <tr>
    <td><%= drug_allergy.name %></td>
    <td><%= drug_allergy.patient %></td>
    <td><%= link_to 'Show', [drug_allergy.patient, drug_allergy] %></td>
    <td><%= link_to 'Edit', edit_patient_drug_allergy_path(drug_allergy.patient, drug_allergy) %></td>
    <td><%= link_to 'Destroy', [drug_allergy.patient, drug_allergy], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drug allergy', new_patient_drug_allergy_path(params[:patient_id]) %>

app/views/drug_allergies/new.html.erb
<h2 class="text-center text-decoration-underline">Add A Drug Allergy To Patient</h2>

<%= render 'form' %>

<div class="text-center">
        <%= link_to 'Back', (@drug_allergy.patient) , class: "btn btn-danger btn-lg" %>
</div>

app/views/drug_allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @drug_allergy.name %>
</p>

<p>
  <b>Patient:</b>
  <%= @drug_allergy.patient %>
</p>


<%= link_to 'Edit', edit_patient_drug_allergy_path(@drug_allergy.patient, @drug_allergy) %> |
<%= link_to 'Back', patient_drug_allergies_path(@drug_allergy.patient) %>