config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patients do
    resources :pre_existing_conditions
    resources :food_allergies
    resources :drug_allergies
  end
  devise_for :doctors
  root to: "doctors#index"

  devise_scope :doctor do
    get '/doctors/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/patient.rb
# rubocop: disable Metrics/MethodLength

class Patient < ApplicationRecord
  has_many :drug_allergies
  has_many :food_allergies
  has_many :pre_existing_conditions
  belongs_to :doctor

  has_one_attached :qr_code
  has_one_attached :image

  include Rails.application.routes.url_helpers

  after_create :generate_qr
  def generate_qr
    qr_url = url_for(controller: 'patients',
                     action: 'show',
                     id: id,
                     only_path: false,
                     host: 'localhost:3000',
                     source: 'from_qr')
    qrcode = RQRCode::QRCode.new(qr_url)

    png = qrcode.as_png(
      resize_gte_to: false,
      resize_exactly_to: false,
      fill: 'white',
      color: 'black',
      size: 120,
      border_modules: 4,
      module_px_size: 6,
      file: nil # path to write
    )
    image_name = SecureRandom.hex
    File.binwrite("tmp/#{image_name}.png", png.to_s)

    blob = ActiveStorage::Blob.create_and_upload!(
      io: File.open("tmp/#{image_name}.png"),
      filename: image_name,
      content_type: 'png'
    )

    qr_code.attach(blob)
  end
end
# rubocop: enable Metrics/MethodLength

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # before_action :authenticate_doctor!, only: %i[index new edit create update destroy]
  before_action :set_patient, only: %i[show edit update destroy]

  # GET /patients or /patients.json
  def index
    @patients = Patient.includes(:doctor).where(doctor_id: current_doctor.id)
  end

  # GET /patients/1 or /patients/1.json
  def show; end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit; end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.doctor_id = current_doctor.id

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: 'Patient was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: 'Patient was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :national_id, :image, :telephone, :gender, :date_of_birth)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">   

      <div class="form-group d-flex justify-content-center">
        <div class="d-flex flex-column">

              <%= form.label :date_of_birth, class: "form-label d-flex justify-content-start" %>
              <%= form.date_field :date_of_birth , class: "form-control w-100" %>
          </div>
      </div>
  
      <div class="form-group d-flex justify-content-center">
        <div class="d-flex flex-column">
       
          <%= form.label :first_name, class: "form-label d-flex justify-content-start" %>
          <%= form.text_field :first_name , class: "form-control" %>
          </div>
      </div>

      <div class="form-group d-flex justify-content-center">
          <div class="d-flex flex-column">
        
            <%= form.label :last_name, class: "form-label d-flex justify-content-start" %>
            <%= form.text_field :last_name , class: "form-control" %>
            </div>
      </div>

     


      <div class="form-group d-flex justify-content-center">
          <div class="d-flex flex-column">
                <label class="form-label d-flex justify-content-start">National Id Number</label>

                <%= form.number_field :national_id , class: "form-control" %>
            </div>
      </div>

   


       
      <div class="form-group d-flex justify-content-center">
          <div class="d-flex flex-column">
        
                <%= form.label :telephone, class: "form-label d-flex justify-content-start" %>
                <%= form.text_field :telephone , class: "form-control" %>
            </div>
      </div>


      <div class="form-group d-flex justify-content-center">
          <div class="d-flex flex-column">
        
                <%= form.label :gender, class: "form-label d-flex justify-content-start" %>
                <%= form.text_field :gender , class: "form-control" %>
            </div>
      </div>
         
      <div class="form-group d-flex justify-content-center">
          <div class="d-flex flex-column">
        
                <%= form.label :image, class: "form-label d-flex justify-content-start" %>
                <%= form.file_field :image , class: "form-control" %>
            </div>
      </div>



      <div>
        <%= form.submit "Add a Patient", class: "btn btn-primary btn-lg" %>
        </div>
    

<% end %>

app/views/patients/_indexpatient.html.erb
<div id="<%= dom_id patient %>">
<tbody>
 <tr>
                     <th scope="row">
                      <div class="media align-items-center">
                        <%= link_to patient_path(patient) , class: "avatar rounded-circle mr-3" do %>
                        
                         <%= image_tag  patient.image %>
            
                        <% end %>
                        <div class="media-body">
                          <span class="mb-0 text-sm"></span>
                        </div>
                      </div>
                    </th>
                    <td>
                      <%= patient.first_name %>
                    </td>
                    <td>
                      <span class="mb-0 text-sm"><%= patient.last_name %></span>
                    
                    </td>
                    <td>
                      <div class="d-flex align-items-center">
                        <span class="mr-2"><%= patient.national_id %></span>
                      </div>
                    </td>
                    <td>
                      <span class="mb-0 text-sm"><%= patient.gender %></span>
                    
                    </td>
                   
                  </tr>
</tbody>

app/views/patients/_patient.html.erb
<div class="container" id="<%= dom_id patient %>">
  <div class="patient-info d-flex justify-content-between">
    
    <section class= "patient-name">
      <h4>Patient details </h4>
        <table class="table table-success table-striped table-bordered">
          <tbody>
          <tr>
              <th scope="row">Image</th>
              <td class="patient-image"><%= image_tag patient.image, class: "img-fluid" %></td>
            <tr>
              <th scope="row">First Name</th>
              <td><%= patient.first_name %></td>
            </tr>
            <tr>
              <th scope="row">Last Name</th>
              <td><%= patient.last_name %></td>
            </tr>
            <tr>
              <th scope="row">National ID</th>
              <td><%= patient.national_id %></td>
            </tr>
            <tr>
              <th scope="row">Telephone</th>
              <td><%= patient.telephone %></td>
            </tr>
            <tr>
              <th scope="row"> Gender</th>
              <td><%= patient.gender %></td>
            </tr>
          </tbody>
      </table>
    </section>
    <section class="patient-condition">

        <h4>Pre Existing Conditions</h4>
        <ul class="conditions-list ">
          <% patient.pre_existing_conditions.each do |pre_existing_condition| %>
            <li>Diabetes:
            <% if pre_existing_condition.diabetes == true %>
              <button class="btn btn-danger px-3">Patient has history of diabetes</button>
            <% else %>
              <button class="btn btn-success px-3">Patient has no history of diabetes</button>
            <% end %>
            </li>
            <li>Hypertension:
            <% if pre_existing_condition.hypertension == true %>
              <button class="btn btn-danger px-3">Patient has history of hypertension</button>
            <% else %>
              <button class="btn btn-success px-3">Patient has no history of hypertension</button>
            <% end %>
            </li>
            <li>Asthma:
            <% if pre_existing_condition.asthma == true %>
              <button class="btn btn-danger px-3">Patient has history of asthma</button>
            <% else %>
              <button class="btn btn-success px-3">Patient has no history of asthma</button>
            <% end %>
            </li>
            <button class="btn btn-dark text-light"><%= link_to "Edit", edit_patient_pre_existing_condition_path(patient, pre_existing_condition) , class: "text-light" %></button>
          <% end %>
        </ul>

        <% if @patient.pre_existing_condition_count == 0 %>
        <%= link_to "Add pre existing condition" , new_patient_pre_existing_condition_path(@patient) %>
        <% end %>


      <hr>

      <div class="patient-allergies">
      <section class="food-allergies d-flex">
            <table class="table table-striped table-primary mx-2">
                <thead>
                  <tr>
                    <th scope="col">Food Allergy:<%=patient.food_allergies.length %></th>
                  </tr>
                </thead>
              <tbody>
              <% if patient.food_allergies.length>0 %>
              <% patient.food_allergies.map do |food_allergy| %>
                <tr>
                  <td><%= food_allergy.name %></td>
                </tr>
              <% end %>
              <% end %>
              </tbody>
            </table>


            <table class="table table-striped table-info">
                <thead>
                  <tr>
                    <th scope="col">Drug Allergy:<%=patient.drug_allergies.length %></th>
                  </tr>
                </thead>
              <tbody>
                <% if patient.drug_allergies.length>0 %>
                <% patient.drug_allergies.map do |drug_allergy| %>
                  <tr>
                    <td><%= drug_allergy.name %></td>
                  </tr>

              <% end %>
              <% end %>
              </tbody>
            </table>
      </section>
        <div class="add-buttons text-center" >
            <button class="btn btn-light"><%= link_to "Add food allergy" , new_patient_food_allergy_path(@patient) %></button>
            <button class="btn btn-light ms-5"><%= link_to "Add drug allergy" , new_patient_drug_allergy_path(@patient) %></button>
        </div>

      </div>
      </section>

      </div>

    </section>
  </div>
</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>



<h1 class="text-center">Patients</h1>



<div id="patients">
  <div class="main-content">
    <div class="container mt-7">
      <!-- Table -->
        <div class="col">
          <div class="card shadow">
            <div class="table-responsive">
              <table class="table align-items-center table-flush w-100">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort" data-sort="name"></th>
                    <th scope="col">first name</th>
                    <th scope="col">last name</th>
                    <th scope="col">National id</th>
                    <th scope="col">gender</th>
                    
                  </tr>
                </thead>
              
      
  <% @patients.each do |patient| %>
    <%= render "patients/indexpatient", patient: patient %>

  <% end %>
  </table>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>


<div class="d-flex justify-content-center my-4">
  <%= link_to "New patient", new_patient_path,class: "btn btn-primary text-align-center" %>
</div>

app/views/patients/new.html.erb
<h2 class="text-center text-decoration-underline">Add A New Patient   </h2>

    <%= render "form", patient: @patient %>


<br>

<div>
  <%= link_to "Back to patients", patients_path , class: "btn btn-danger btn-lg" %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>



<%= render @patient %>
<div class="text-start mx-4 mb-5">
  <p>
    <%= image_tag(@patient.qr_code) if @patient.qr_code.attached? %>
  </p>
</div>


<div class="text-center">
  <%= link_to "Back to patients", patients_path , class: "btn btn-danger btn-lg" %>


</div>



<div>


</div>