config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patients do
    resources :pre_existing_conditions
    resources :food_allergies
    resources :drug_allergies
  end
  devise_for :doctors
  root to: "doctors#index"

  devise_scope :doctor do
    get '/doctors/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food_allergy.rb
class FoodAllergy < ApplicationRecord
  belongs_to :patient
end

app/controllers/food_allergies_controller.rb
class FoodAllergiesController < ApplicationController
  before_action :set_patient
  before_action :set_food_allergy, only: %i[show edit update destroy]

  # GET patients/1/food_allergies
  def index
    @food_allergies = @patient.food_allergies
  end

  # GET patients/1/food_allergies/1
  def show; end

  # GET patients/1/food_allergies/new
  def new
    @food_allergy = @patient.food_allergies.build
  end

  # GET patients/1/food_allergies/1/edit
  def edit; end

  # POST patients/1/food_allergies
  def create
    @food_allergy = @patient.food_allergies.build(food_allergy_params)

    if @food_allergy.save
      redirect_to(@food_allergy.patient)
    else
      render action: 'new'
    end
  end

  # PUT patients/1/food_allergies/1
  def update
    if @food_allergy.update_attributes(food_allergy_params)
      redirect_to([@food_allergy.patient, @food_allergy], notice: 'Food allergy was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE patients/1/food_allergies/1
  def destroy
    @food_allergy.destroy

    redirect_to patient_food_allergies_url(@patient)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def set_food_allergy
    @food_allergy = @patient.food_allergies.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def food_allergy_params
    params.require(:food_allergy).permit(:name, :patient_id)
  end
end

app/views/food_allergies/_form.html.erb
<%= form_for([@food_allergy.patient, @food_allergy]) do |f| %>
  <% if @food_allergy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_allergy.errors.count, "error") %> prohibited this food_allergy from being saved:</h2>

      <ul>
      <% @food_allergy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 

   <div class="text-center">
        
        <%= f.text_field :name %>
      </div>


  <div class="text-center">
    <%= f.submit  class: "btn btn-primary my-3" %>
  </div>
<% end %>

app/views/food_allergies/edit.html.erb
<h1>Editing food_allergy</h1>

<%= render 'form' %>

<%= link_to 'Show', [@food_allergy.patient, @food_allergy] %> |
<%= link_to 'Back', patient_food_allergies_path(@food_allergy.patient) %>

app/views/food_allergies/index.html.erb
<h1>Listing food_allergies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Patient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @food_allergies.each do |food_allergy| %>
  <tr>
    <td><%= food_allergy.name %></td>
    <td><%= food_allergy.patient %></td>
    <td><%= link_to 'Show', [food_allergy.patient, food_allergy] %></td>
    <td><%= link_to 'Edit', edit_patient_food_allergy_path(food_allergy.patient, food_allergy) %></td>
    <td><%= link_to 'Destroy', [food_allergy.patient, food_allergy], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food allergy', new_patient_food_allergy_path(params[:patient_id]) %>

app/views/food_allergies/new.html.erb
<h2 class="text-center text-decoration-underline">Add A Food Allergy To Patient</h2>
    <%= render 'form' %>

<div class="text-center">
        <%= link_to 'Back', (@food_allergy.patient) , class: "btn btn-danger btn-lg" %>
</div>

app/views/food_allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @food_allergy.name %>
</p>

<p>
  <b>Patient:</b>
  <%= @food_allergy.patient %>
</p>


<%= link_to 'Edit', edit_patient_food_allergy_path(@food_allergy.patient, @food_allergy) %> |
<%= link_to 'Back', patient_food_allergies_path(@food_allergy.patient) %>