config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patients do
    resources :pre_existing_conditions
    resources :food_allergies
    resources :drug_allergies
  end
  devise_for :doctors
  root to: "doctors#index"

  devise_scope :doctor do
    get '/doctors/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <% if doctor_signed_in? %> 
     <h2 class="navbar-brand" > Welcome , <%= current_doctor.name %> </h2>
    <% else %>
      <h2 class="navbar-brand"> Not a member ? <h2>
    <% end %>   

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if doctor_signed_in? %>
        
             <li class="nav-item">
               <%= link_to "Patients", patients_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
               <%= link_to "Add a patient", new_patient_path, class: "nav-link" %>
            </li>
        <% else %>
           <li class="nav-item">
              <%= link_to "Sign up" , new_doctor_registration_path , class: "btn btn-outline-success mx-4"%>
            </li>
            <li class="nav-item">
               <%= link_to "Sign in" , new_doctor_session_path , class: "btn btn-outline-success"%>
            </li>
        <% end %>    


        
       </ul>
       <% !if doctor_signed_in? %>
      <form class="d-flex" role="search">
          <%= link_to "Sign Out", destroy_doctor_session_path , class: "btn btn-outline-danger" %>

      </form>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    
  </head>
  <body>
    
   
    <%= render "layouts/header" %>
  
    <%= yield %>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    
  </body>
</html>